### PR TITLE
Add optional resource route filtering with 'only:'

### PR DESCRIPTION
**Pull request by alexdavid**
Moving #12 over to this repo to finish up the PR

### CODE REVIEW

**Comment by alexdavid** [comment]
@jondistad I renamed the non-get routes to their controller action names. What do you think about that?

**Comment by charlierudolph** [comment]
Why would the non-get routes have their own route names? Rails routing has the same urls result in the same helpers: show, update, delete are all the same and create, index are the same

**Comment by alexdavid** [comment]
I didn't know that. How does rails' `form_for(url: user_path)` know what method to use then?

**Comment by charlierudolph** [comment]
`form_for` requires an object and it check whether or not its been persisted.

**Comment by charlierudolph** [comment]
Update the README if `resources` is now defining update, create, and destroy specific reverse routes

**Comment by catharinejm** [comment]
In Rails if you need to specify 'update' over 'show' you would include a `method: put` somewhere.

E.g.

``` ruby
form_for user, url: user_path, html: {method: :put}
# or
link_to "Delete", user_path, method: :delete
```

Since the 'show', 'update' and 'destroy' routes are the same, they use the same path helper, you just use a different HTTP verb when you make the request. Even if you have `destroy_user_path` you still have to specify `DELETE`, so it becomes redundant. The same is true for 'index' and 'create'.

**Comment by alexdavid** [comment]
I agree if you have to specify the http method manually having separate routes is redundant. What are your thoughts around #19 and having a separate `routes` hash?

**Comment by alexdavid** [comment]
I'm going to merge this for now and refactor the routes hash in a separate PR

**Pull request closed without merging**
