### PR TITLE
set this.routes in controllers

### PR DESCRIPTION
**Pull request by charlierudolph**
@alexdavid @kevgo

### CODE REVIEW

**Comment by kevgo** [comment]
Can we set `this.routes` in addition to `res.local.routes`? The `this` object is notoriously ephemeral in JS. So I see the benefit of providing a shortcut to `this.routes`, while also seeing the benefit of providing properly namespaced access through the response object. Actually, shouldn't it be at the request object?

**Comment by kevgo** [comment]
Anyways, :ship: from my end since I don't feel strongly either way here.

**Comment by charlierudolph** [comment]
`res.locals.routes` is still set. Its just setting this.routes in controllers for easier access in controllers. `res.local.routes` is still there for ease of use in views.

**Comment by kevgo** [comment]
Cool!

**Comment by alexdavid** [comment]
Thanks Charlie!

Ship it

**Pull request closed without merging**
